name: esther_gift
description: "A Rogulike Card Game Made with Flutter."
publish_to: "none"
version: 0.2.0+1

environment:
    sdk: ^3.11.3

dependencies:
    flutter:
        sdk: flutter
    mobile_scanner: ^7.2.0
    qr_flutter: ^4.1.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^6.0.0

flutter:
    uses-material-design: true
